In [1]:
from py.typyMagics import typyMagics
ip = get_ipython()
ip.register_magics(typyMagics)

In [3]:
%%run_and_write py/test.py
def test(blargh):
    pass

Overwriting py/test.py


<function __main__.testt>

In [1]:
import numpy as np
A = np.random.rand(1000,3,3)
def slow_inverse(A): 
    Ainv = np.zeros_like(A)

    for i in range(A.shape[0]):
        Ainv[i] = np.linalg.inv(A[i])
    return Ainv

def fast_inverse(A):
    identity = np.identity(A.shape[2], dtype=A.dtype)
    Ainv = np.zeros_like(A)

    for i in range(A.shape[0]):
        Ainv[i] = np.linalg.solve(A[i], identity)
    return Ainv

def fast_inverse2(A):
    identity = np.identity(A.shape[2], dtype=A.dtype)

    return array([np.linalg.solve(x, identity) for x in A])

from numpy.linalg import lapack_lite
lapack_routine = lapack_lite.dgesv
# Looking one step deeper, we see that solve performs many sanity checks.  
# Stripping these, we have:
def faster_inverse(A):
    b = np.identity(A.shape[2], dtype=A.dtype)

    n_eq = A.shape[1]
    n_rhs = A.shape[2]
    pivots = zeros(n_eq, np.intc)
    identity  = np.eye(n_eq)
    def lapack_inverse(a):
        b = np.copy(identity)
        pivots = zeros(n_eq, np.intc)
        results = lapack_lite.dgesv(n_eq, n_rhs, a, n_eq, pivots, b, n_eq, 0)
        if results['info'] > 0:
            raise LinAlgError('Singular matrix')
        return b

    return array([lapack_inverse(a) for a in A])


%timeit -n 20 aI11 = slow_inverse(A)
%timeit -n 20 aI12 = fast_inverse(A)
%timeit -n 20 aI13 = fast_inverse2(A)
%timeit -n 20 aI14 = faster_inverse(A)

AttributeError: module 'numpy.linalg.lapack_lite' has no attribute 'dgesv'

In [16]:
A = [[2,1,0],[2,0,0],[2,0,1]]
B = np.array([A,A,A,A,A])
print(B)
print(np.linalg.inv(B))
print(np.linalg.inv(A))



[[[2 1 0]
  [2 0 0]
  [2 0 1]]

 [[2 1 0]
  [2 0 0]
  [2 0 1]]

 [[2 1 0]
  [2 0 0]
  [2 0 1]]

 [[2 1 0]
  [2 0 0]
  [2 0 1]]

 [[2 1 0]
  [2 0 0]
  [2 0 1]]]
[[[ 0.   0.5  0. ]
  [ 1.  -1.  -0. ]
  [ 0.  -1.   1. ]]

 [[ 0.   0.5  0. ]
  [ 1.  -1.  -0. ]
  [ 0.  -1.   1. ]]

 [[ 0.   0.5  0. ]
  [ 1.  -1.  -0. ]
  [ 0.  -1.   1. ]]

 [[ 0.   0.5  0. ]
  [ 1.  -1.  -0. ]
  [ 0.  -1.   1. ]]

 [[ 0.   0.5  0. ]
  [ 1.  -1.  -0. ]
  [ 0.  -1.   1. ]]]
[[ 0.   0.5  0. ]
 [ 1.  -1.  -0. ]
 [ 0.  -1.   1. ]]


SyntaxError: Missing parentheses in call to 'print' (<ipython-input-4-bc57f94b427c>, line 1)